### ISSUE TITLE
Integration

### ISSUE THREAD

**Issue by wrux** [continuous-software/node-linnworks#1]
How can I get this integrated into my app. I need to use it to sync between ChannelAdvisor and I have found a package for that but this does not give any documentation on how to implement it. 

I also need to use a API token for Linnworks and looking at the code I cannot see how I would use this.

**Comment by ghost** [comment]
It's just a wrapper that consume their SOAP api using `node-soap`. Here's an example:

``` javascript
 var generic = new linnworks.generic(function(error, genericClient) {
        genericClient.GenerateToken({email: EMAIL, password: PASSWORD}, function(error, result, xml) {
            genericClient.GetPackagingGroups({
              Token: token
            }, function (error, result, xml) {
            });
        })
});
```

This package is in its really early stage though, possible that it encounter breaking changes anytime soon.
Refer to the [documentation](http://www.linnworks.com/Doc/API_Reference) for more infos meanwhile.
